/// Generated by AssetsRefGenerator on 2020/07/01
class Res {
  static const String workspace = "assets/files/.idea/workspace.xml";
  static const String index = "assets/files/css/index.css";
  static const String client = "assets/files/js/client.js";
  static const String photo = "assets/files/photo.html";
  static const String iconfont = "assets/fonts/iconfont.json";
  static const String A171 = "assets/image/A171.jpg";
  static const String headIcon = "assets/image/headIcon.png";
  static const String Icon_Mac = "assets/image/Icon_Mac.png";
  static const String IMG_3601 = "assets/image/IMG_3601.JPG";
  static const String placeholderImage = "assets/image/placeholderImage.png";
  static const String tongxunlu = "assets/image/tongxunlu.png";
}
